theme: jekyll-theme-minimal

title: "Machine Translation"

email: loaicigasanchez@uni-potsdam.de

search_enabled: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

aux_links:
  "All Classes":
  - "//github.com/compling-potsdam"

permalink: pretty

